sudo: false

addons:
  apt:
    packages:
      - libgmp-dev

install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.3.1/stack-0.1.3.1-x86_64-linux.gz | gunzip > ~/.local/bin/stack
  - chmod a+x ~/.local/bin/stack
  - stack --version

script:
  - stack setup
  - stack build --ghc-options=-Werror
  - stack test --ghc-options=-Werror

  # detecting dead code in this project
  - stack exec ghc-pkg expose ghc
  - stack exec -- dead-code-detection --root Main -isrc -idriver
  - stack exec -- dead-code-detection --root Main -isrc -itest

cache:
  directories:
    - $HOME/.stack
