sudo: false

env:
  - GHCVER=7.10.1

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.10.1
      - cabal-install-1.22
      - happy-1.19.5

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/1.22/bin:/opt/happy/1.19.5/bin:$PATH
  - ghc --version
  - cabal --version
  - happy --version
  - travis_retry cabal update
  - cabal install --enable-tests --only-dep

script:
  - cabal configure --enable-tests --ghc-options=-Werror && cabal build && cabal test
  - cabal install --ghc-options=-Werror
