ghc-options: -Wall -fno-warn-name-shadowing

dependencies:
  - base == 4.*
  - silently
  - getopt-generics
  - ghc
  - Glob
  - string-conversions
  - graph-wrapper
  - containers
  - uniplate
  - ghc-paths

executables:
  dead-code-detection:
    main: Main.hs
    source-dirs:
      - src

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - mockery
      - interpolate
      - filepath
