name: find-dead-code

executables:
  find-dead-code:
    main: Main.hs
    dependencies:
      - ghc-paths
      - uniplate

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - mockery
      - interpolate
