name: find-dead-code

ghc-options: -Wall -fno-warn-name-shadowing

dependencies:
  - base == 4.*
  - silently

executables:
  find-dead-code:
    main: Main.hs
    source-dirs:
      - src
    dependencies:
      - ghc
      - ghc-paths
      - uniplate
      - graph-wrapper
      - string-conversions

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - mockery
      - interpolate
